services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oss_sentinel_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: oss_sentinel_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
